spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
